name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"   # UTC 20:00 = JST 05:00

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      PYTHONUTF8: "1"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps
        run: |
          python -V
          python -m pip install -U pip
          python -m pip install -r requirements.txt pytest pytest-cov

      - name: Clean workspace
        run: make clean || true

      # 建好資料管線（ingest → silver → gold → validate → demo）
      - name: Build pipeline
        run: make run

      # 冪等性 + 單元測試 + quarantine 比例門檻
      - name: Check (idempotency + tests + quarantine)
        run: make check

      # 產物上傳：失敗也上傳，方便除錯
      - name: Upload report/artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gold-and-dq
          retention-days: 7
          if-no-files-found: warn
          path: |
            data/gold/fact_sales.csv
            reports/dq_report.md
